Repository bounswe/bounswe2018group5, pull requests merged in 2018-12, with the labels that each got.

#298 Implement Projects fragment, fix endpoints
  android/app/build.gradle
  android/app/src/main/java/com/karpuz/karpuz/Activity/HomeActivity.kt
  android/app/src/main/java/com/karpuz/karpuz/Adapter/ProjectsAdapter.kt
  android/app/src/main/java/com/karpuz/karpuz/Fragment/ProjectsFragment.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/Config.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPI.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIModels.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIService.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/MockKarpuzAPIProvider.kt
  android/app/src/main/res/drawable/profile_placeholder.png
  android/app/src/main/res/layout/fragment_projects.xml
  android/app/src/main/res/layout/project_cell.xml
  android/app/src/main/res/values/strings.xml
Labels: Platform: Android, Priority: High, Type: Enhancement

#299 191 implement project creation
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/karpuz/karpuz/Activity/CreateProjectActivity.kt
  android/app/src/main/java/com/karpuz/karpuz/Activity/HomeActivity.kt
  android/app/src/main/java/com/karpuz/karpuz/Adapter/ProjectsAdapter.kt
  android/app/src/main/java/com/karpuz/karpuz/Fragment/ProjectsFragment.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPI.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIModels.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIProvider.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/KarpuzAPIService.kt
  android/app/src/main/java/com/karpuz/karpuz/Network/MockKarpuzAPIProvider.kt
  android/app/src/main/res/drawable/profile_icon.png
  android/app/src/main/res/drawable/profile_placeholder.png
  android/app/src/main/res/drawable/project_header_gradient.xml
  android/app/src/main/res/drawable/side_nav_bar.xml
  android/app/src/main/res/layout/activity_create_project.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_signup.xml
  android/app/src/main/res/layout/fragment_projects.xml
  android/app/src/main/res/layout/nav_header_home.xml
  android/app/src/main/res/layout/project_cell.xml
  android/app/src/main/res/menu/activity_home_drawer.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
Labels: Platform: Android, Status: Available, Type: Enhancement

#303 attachments functionality- #294
  backend/api/attachment.py
  backend/api/urls.py
  backend/api/utils.py
  backend/project/models.py
  backend/user/models.py
  backend/user/views.py
Labels: Effort: Low, Platform: API, Priority: High, Status: Review Needed, Type: Help Wanted

#307 add Project attachment upload and delete
  frontend/src/views/ProjectPage/ProjectPage.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#309 Register validation with api response.
  frontend/src/components/Form/RegisterForm.jsx
  frontend/src/redux/auth/Reducer.js
  frontend/src/views/ProjectPage/ProjectPage.jsx
Labels: Effort: Low, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#321 after finish rating is active
  frontend/src/components/DropDown/ProjectDropdown.jsx
  frontend/src/redux/project/Actions.js
Labels: Effort: Medium, Platform: Web, Priority: Critical, Status: Completed, Type: Enhancement

#322 add Portfolio Attachments
  frontend/src/components/Card/PortfolioCard.jsx
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: High, Platform: Web, Priority: Critical, Status: Completed, Type: Enhancement

#338 semantic tag features are added-#262
  backend/api/semantic_tags.py
  backend/api/urls.py
  backend/api/utils.py
  backend/project/models.py
  backend/requirements.txt
  backend/user/models.py
Labels: Effort: Medium, Platform: API, Priority: High, Status: Review Needed, Type: Enhancement

#341 Add new editable fields
  frontend/src/components/DropDown/ProjectDropdown.jsx
  frontend/src/redux/project/Actions.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
Labels: Effort: Low, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#342 linkedin profile integration
  frontend/.env-example
  frontend/src/components/Modal/AddPortfolioModal.jsx
  frontend/src/services/LinkedIn.jsx
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#344 #319 - Prevent multiple ratings for a project
  backend/user/views.py
Labels: Effort: Low, Platform: API, Priority: Critical, Status: Completed, Type: Bug

#346 Add publicity to project get endpoint
  backend/api/utils.py
  backend/project/views.py
  backend/user/views.py
Labels: Effort: Medium, Platform: API, Priority: High, Status: Completed, Type: Enhancement

#348 Recommendation backend
  backend/api/recommendation_engine.py
  backend/api/semantic_tags.py
  backend/api/urls.py
  backend/project/models.py
  backend/requirements.txt
Labels: Effort: Medium, Platform: API, Priority: High, Status: Review Needed, Type: Help Wanted
