Repository bounswe/bounswe2018group5, pull requests merged in 2018-11, with the labels that each got.

#214 Add sentry.io Integration to Django
  backend/api/settings.py
  backend/requirements.txt
Labels: Effort: Low, Platform: API, Priority: Medium, Status: Completed, Type: Enhancement

#216 Project model modified. Search index created and search endpoint implemented.
  backend/api/settings.py
  backend/project/models.py
  backend/project/urls.py
  backend/project/views.py
  backend/user/views.py
Labels: Effort: Medium, Platform: API, Priority: High, Status: Review Needed, Type: Enhancement

#222 Get own projects endpoint implemented.
  backend/project/urls.py
  backend/project/views.py
Labels: Status: Review Needed

#224 Frontend/other user profile
  frontend/src/components/Card/ProjectCard.jsx
  frontend/src/components/Footer/LoggedInFooter.jsx
  frontend/src/components/Modal/AddProjectModal.jsx
  frontend/src/layouts/Home/Home.jsx
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/redux/user/Actions.js
  frontend/src/redux/user/Reducer.js
  frontend/src/redux/user/actionTypes.js
  frontend/src/views/HomePage/HomePage.jsx
  frontend/src/views/UserProfile/OtherUserProfile.jsx
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#227 Projects page.
  frontend/src/components/Card/ProjectCard.jsx
  frontend/src/components/Header/LoggedInHeader.jsx
  frontend/src/components/Sidebar/Sidebar.jsx
  frontend/src/layouts/Home/Home.jsx
  frontend/src/redux/project/Actions.js
  frontend/src/redux/project/Reducer.js
  frontend/src/redux/project/actionTypes.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/views/HomePage/HomePage.jsx
  frontend/src/views/ProjectPage/ProjectPage.jsx
  frontend/src/views/ProjectsPage/ProjectsPage.jsx
  frontend/src/views/UserProfile/OtherUserProfile.jsx
Labels: Effort: Medium, Platform: Web, Status: Completed, Type: Enhancement

#230 Bid model and endpoints w/ minor changes
  backend/project/models.py
  backend/project/urls.py
  backend/project/views.py
Labels: Effort: High, Platform: API, Priority: High, Status: Review Needed

#231 Login Logout bug fixed.
  frontend/src/components/Form/LoginForm.jsx
  frontend/src/components/Sidebar/Sidebar.jsx
  frontend/src/redux/auth/Reducer.js
  frontend/src/routes/PrivateRoute.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Bug

#233 Add project edit, discard and delete components.
  frontend/src/components/Badge/Badge.jsx
  frontend/src/components/Card/ProjectCard.jsx
  frontend/src/components/DateTimePicker/DateTimePicker.jsx
  frontend/src/components/DropDown/ProjectDropdown.jsx
  frontend/src/components/Modal/AddProjectModal.jsx
  frontend/src/services/combineStyles.js
  frontend/src/views/HomePage/HomePage.jsx
  frontend/src/views/ProjectsPage/ProjectsPage.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#237 Connect API connections for discard project and edit project.
  frontend/src/components/Card/ProjectCard.jsx
  frontend/src/components/DateTimePicker/DateTimePicker.jsx
  frontend/src/components/DropDown/ProjectDropdown.jsx
  frontend/src/components/Modal/AddProjectModal.jsx
  frontend/src/redux/project/Actions.js
  frontend/src/redux/project/Reducer.js
  frontend/src/redux/project/actionTypes.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/views/HomePage/HomePage.jsx
  frontend/src/views/ProjectsPage/ProjectsPage.jsx
Labels: Effort: High, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#239 API connection for project page.
  frontend/src/redux/project/Actions.js
  frontend/src/redux/project/Reducer.js
  frontend/src/redux/project/actionTypes.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/views/ProjectPage/ProjectPage.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#241 Project flow
  frontend/src/components/Bids/Bids.jsx
  frontend/src/components/CreateBid/CreateBid.jsx
  frontend/src/components/DropDown/BidDropdown.jsx
  frontend/src/components/Modal/CreateBidModal.jsx
  frontend/src/components/Sidebar/Sidebar.jsx
  frontend/src/redux/project/Actions.js
  frontend/src/redux/project/Reducer.js
  frontend/src/redux/project/actionTypes.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/routes/PrivateRoute.jsx
  frontend/src/services/cookies.js
  frontend/src/views/ProjectPage/ProjectPage.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#246 Accept bid changes
  backend/project/views.py
Labels: Effort: Low, Platform: API, Priority: Medium, Status: Review Needed, Type: Maintenance

#248 Rating model and endpoints
  backend/api/utils.py
  backend/project/views.py
  backend/user/models.py
  backend/user/urls.py
  backend/user/views.py
Labels: Effort: High, Platform: API, Status: Review Needed, Type: Enhancement

#258 Fix all used endpoints.
  frontend/src/redux/sagas/api.js
  frontend/src/services/HttpService.js
Labels: Effort: Medium, Priority: Critical, Status: Completed, Type: Bug

#259 Portfolio model and endpoints
  backend/api/utils.py
  backend/user/models.py
  backend/user/urls.py
  backend/user/views.py
Labels: Effort: High, Platform: API, Priority: Medium, Status: Review Needed, Type: Enhancement

#270 Project enhancements
  backend/api/utils.py
  backend/project/models.py
  backend/project/urls.py
  backend/project/views.py
Labels: Effort: Medium, Platform: API, Priority: High, Status: Review Needed, Type: Enhancement

#271 Edit portfolio is added
  frontend/src/components/DateTimePicker/DateTimePicker.jsx
  frontend/src/components/DropDown/PortfolioDropdown.jsx
  frontend/src/components/DropDown/ProjectDropdown.jsx
  frontend/src/views/UserProfile/OtherUserProfile.jsx
Labels: Effort: Low, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#275 HOTFIX - Fixed project field on DELETE project
  backend/project/views.py
Labels: Effort: Low, Platform: API, Priority: Critical, Status: Completed, Type: Bug

#278 #276 - Date formatting
  backend/api/utils.py
Labels: Effort: Low, Platform: API, Priority: Critical, Status: Completed, Type: Maintenance

#287 F wallet
  frontend/README.md
  frontend/src/components/DropDown/PortfolioDropdown.jsx
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/redux/user/Actions.js
  frontend/src/redux/user/Reducer.js
  frontend/src/redux/user/actionTypes.js
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#291 Feature profile image
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: High, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#297 Add milestone model and endpoints
  backend/api/utils.py
  backend/project/models.py
  backend/project/urls.py
  backend/project/views.py
Labels: Effort: Medium, Platform: API, Priority: High, Status: Review Needed, Type: Enhancement
