Repository bounswe/bounswe2018group5, pull requests merged in 2018-04, with the labels that each got.

#106 Initialize Boilerplate
  .gitignore
  KarpuzTwitterApp/.env-example
  KarpuzTwitterApp/.gitignore
  KarpuzTwitterApp/README.md
  KarpuzTwitterApp/app.py
  KarpuzTwitterApp/end_points.py
  KarpuzTwitterApp/handlers/base.py
  KarpuzTwitterApp/handlers/main.py
  KarpuzTwitterApp/requirements.txt
  KarpuzTwitterApp/settings.py
  KarpuzTwitterApp/static/css/bootstrap.min.css
  KarpuzTwitterApp/static/css/offcanvas.css
  KarpuzTwitterApp/static/favicon.ico
  KarpuzTwitterApp/static/js/bootstrap.min.js
  KarpuzTwitterApp/static/js/ie10-viewport-bug-workaround.js
  KarpuzTwitterApp/static/js/offcanvas.js
  KarpuzTwitterApp/templates/index.html
Labels: Effort: Medium, Priority: Medium, Status: In Progress, Type: Enhancement

#108 Update boilerplate codes.
  KarpuzTwitterApp/.env-example
  KarpuzTwitterApp/README.md
  KarpuzTwitterApp/settings.py
  KarpuzTwitterApp/templates/index.html
Labels: Effort: Low, Platform: Web, Priority: High, Status: Review Needed, Type: Maintenance

#109 Adds missing parts and changing HTML structure.
  KarpuzTwitterApp/README.md
  KarpuzTwitterApp/handlers/main.py
  KarpuzTwitterApp/requirements.txt
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/main.html
Labels: Effort: Low, Platform: Web, Priority: High, Status: In Progress, Type: Maintenance

#110 Parcel main.html
  KarpuzTwitterApp/templates/main.html
Labels: Effort: Low, Platform: Web, Priority: High, Status: In Progress, Type: Maintenance

#111 Tweets with location
  KarpuzTwitterApp/.env-example
  KarpuzTwitterApp/.gitignore
  KarpuzTwitterApp/end_points.py
  KarpuzTwitterApp/handlers/locationtweets.py
  KarpuzTwitterApp/handlers/main.py
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/requirements.txt
  KarpuzTwitterApp/static/css/bootstrap.min.css
  KarpuzTwitterApp/static/js/helper.js
  KarpuzTwitterApp/static/js/selector.js
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/locationtweets.html
  KarpuzTwitterApp/templates/main.html
  KarpuzTwitterApp/utils/TwitterService.py
Labels: Effort: Medium, Platform: Web, Priority: Medium, Status: Review Needed, Type: Maintenance

#113 Include some improvements
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/locationtweets.html
Labels: Effort: Low, Priority: Low, Status: Completed, Type: Maintenance

#117 Added User Timeline function.
  KarpuzTwitterApp/end_points.py
  KarpuzTwitterApp/handlers/usertimeline.py
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/main.html
  KarpuzTwitterApp/templates/usertimeline.html
Labels: Effort: Medium, Priority: High, Status: Review Needed, Type: Maintenance

#116 Fix Singleton Python3 Bug and add HTTP500 template html
  KarpuzTwitterApp/handlers/base.py
  KarpuzTwitterApp/templates/HTTP500.html
  KarpuzTwitterApp/utils/TwitterService.py
Labels: Effort: Low, Priority: Medium, Status: In Progress, Type: Bug

#115 Common Followings of Two User
  KarpuzTwitterApp/end_points.py
  KarpuzTwitterApp/handlers/commonfollowings.py
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/templates/commonfollowings.html
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/main.html
Labels: Effort: High, Platform: Web, Priority: Medium, Status: Review Needed, Type: Maintenance

#119 Integrate Common Followers feature
  .gitignore
  KarpuzTwitterApp/end_points.py
  KarpuzTwitterApp/handlers/commonfollowers.py
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/templates/commonfollowers.html
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/main.html
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Review Needed, Type: Enhancement

#120 Add search tweets end points to project
  KarpuzTwitterApp/end_points.py
  KarpuzTwitterApp/handlers/searchtweet.py
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/main.html
  KarpuzTwitterApp/templates/searchtweets.html
Labels: Effort: Medium, Platform: Web, Priority: Medium, Status: Completed, Type: Maintenance

#121 Search users
  KarpuzTwitterApp/end_points.py
  KarpuzTwitterApp/handlers/searchusers.py
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/templates/index.html
  KarpuzTwitterApp/templates/main.html
  KarpuzTwitterApp/templates/searchusers.html
Labels: Effort: Medium, Priority: High, Status: Review Needed, Type: Maintenance
