Repository bounswe/bounswe2018group5, pull requests merged in 2018-10, with the labels that each got.

#144 Helmet Package
  frontend/package.json
  frontend/src/views/LandingPage/LandingPage.jsx
Labels: Effort: Low, Platform: Web, Priority: Medium, Status: In Progress, Type: Enhancement

#137 Design Landing page
  frontend/package.json
  frontend/public/index.html
  frontend/src/assets/img/faces/christian.jpg
  frontend/src/assets/img/landing-bg.jpg
  frontend/src/components/Card/StatCard.jsx
  frontend/src/components/Card/SummaryProjectCard.jsx
  frontend/src/components/Card/TestimonialCard.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Header/HeaderLinks.jsx
  frontend/src/routes/index.jsx
  frontend/src/views/LandingPage/LandingPage.jsx
  frontend/src/views/LandingPage/Sections/ProjectSection.jsx
  frontend/src/views/LandingPage/Sections/StatSection.jsx
  frontend/src/views/LandingPage/Sections/TestimonialSection.jsx
Labels: Effort: Medium, Platform: Web, Priority: Medium, Type: Enhancement

#140 Android Project setup & Boilerplate
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/karpuz/karpuz/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/ic_launcher-web.png
  android/app/src/main/java/com/karpuz/karpuz/Activity/LoginActivity.kt
  android/app/src/main/java/com/karpuz/karpuz/Activity/SignupActivity.kt
  android/app/src/main/java/com/karpuz/karpuz/Activity/WelcomeActivity.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/karpuz_logo.png
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_signup.xml
  android/app/src/main/res/layout/activity_welcome.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/ic_launcher_background.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/test/java/com/karpuz/karpuz/ExampleUnitTest.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
Labels: Platform: Android

#147 Design home page and routing
  frontend/docker-compose-frontend.yml
  frontend/src/assets/img/favicon.ico
  frontend/src/index.js
  frontend/src/layouts/Home/Home.jsx
  frontend/src/routes/index.jsx
  frontend/src/views/HomePage/HomePage.jsx
  frontend/src/views/LandingPage/LandingPage.jsx
  frontend/src/views/LandingPage/Sections/ProjectSection.jsx
  frontend/src/views/LandingPage/Sections/StatSection.jsx
  frontend/src/views/LandingPage/Sections/TestimonialSection.jsx
Labels: Effort: Medium, Platform: Web, Status: In Progress, Type: Enhancement

#138 Design Register Page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FormValidator/FormValidator.js
  frontend/src/components/RegisterForm/RegisterForm.jsx
  frontend/src/index.js
  frontend/src/sign.jpg
  frontend/src/views/LandingPage/LandingPage.jsx
  frontend/src/views/RegisterPage/RegisterPage.jsx
Labels: Effort: Medium, Platform: Web, Priority: Medium, Status: In Progress, Type: Enhancement

#152 Add redux login and register endpoints.
  frontend/.env-example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form/RegisterForm.jsx
  frontend/src/index.js
  frontend/src/redux/auth/Actions.js
  frontend/src/redux/auth/Reducer.js
  frontend/src/redux/auth/actionTypes.js
  frontend/src/redux/configureStore.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/services/HttpService.js
  frontend/src/services/cookies.js
Labels: Effort: Medium, Platform: Web, Priority: Medium, Status: In Progress, Type: Enhancement

#156 authentication functionalities
  .gitignore
  backend/api/settings.py
  backend/api/urls.py
  backend/project/models.py
  backend/project/urls.py
  backend/project/views.py
  backend/requirements.txt
  backend/user/authentication.py
  backend/user/models.py
  backend/user/urls.py
  backend/user/views.py
Labels: Status: Review Needed

#159 Add functionality to register and login button.
  frontend/src/components/CustomInput/CustomInput.jsx
  frontend/src/components/Form/LoginForm.jsx
  frontend/src/components/Form/RegisterForm.jsx
  frontend/src/redux/auth/Actions.js
  frontend/src/redux/auth/Reducer.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/services/HttpService.js
  frontend/src/services/cookies.js
  frontend/src/views/LoginPage/LoginPage.jsx
  frontend/src/views/RegisterPage/RegisterPage.jsx
Labels: Effort: Medium

#160 Develop/frontend
  frontend/.env-example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/img/bg7.jpg
  frontend/src/components/CustomInput/CustomInput.jsx
  frontend/src/components/Form/LoginForm.jsx
  frontend/src/components/Form/RegisterForm.jsx
  frontend/src/index.js
  frontend/src/layouts/Home/Home.jsx
  frontend/src/redux/auth/Actions.js
  frontend/src/redux/auth/Reducer.js
  frontend/src/redux/auth/actionTypes.js
  frontend/src/redux/configureStore.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/services/HttpService.js
  frontend/src/services/cookies.js
  frontend/src/sign.jpg
  frontend/src/views/LoginPage/LoginPage.jsx
  frontend/src/views/RegisterPage/RegisterPage.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#165 Add Private route for not loggedin user redirect to login page.
  frontend/src/index.js
  frontend/src/routes/PrivateRoute.jsx
Labels: Effort: Low, Platform: Web, Priority: Medium, Status: Completed, Type: Enhancement

#168 Add profile page and Home page for loggedin user.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/img/sidebar.jpg
  frontend/src/components/Footer/LoggedInFooter.jsx
  frontend/src/components/Header/LoggedInHeader.jsx
  frontend/src/components/Header/LoggedInHeaderLinks.jsx
  frontend/src/components/Sidebar/Sidebar.jsx
  frontend/src/index.js
  frontend/src/layouts/Home/Home.jsx
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#173 Add Logout and get profile endpoint.
  frontend/src/components/Footer/LoggedInFooter.jsx
  frontend/src/components/Sidebar/Sidebar.jsx
  frontend/src/index.js
  frontend/src/layouts/Home/Home.jsx
  frontend/src/redux/auth/Reducer.js
  frontend/src/redux/configureStore.js
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/redux/user/Actions.js
  frontend/src/redux/user/Reducer.js
  frontend/src/redux/user/actionTypes.js
  frontend/src/routes/PrivateRoute.jsx
  frontend/src/services/HttpService.js
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#179 Update Password and Profile is added.
  frontend/src/redux/sagas/api.js
  frontend/src/redux/sagas/saga.js
  frontend/src/redux/user/Actions.js
  frontend/src/redux/user/Reducer.js
  frontend/src/redux/user/actionTypes.js
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#186 Show projects in the home page.
  frontend/src/components/Card/ProjectCard.jsx
  frontend/src/views/HomePage/HomePage.jsx
Labels: Effort: Medium, Platform: Web, Priority: High, Status: Completed, Type: Enhancement

#188 Add after register autologin
  frontend/src/components/Form/RegisterForm.jsx
  frontend/src/redux/auth/Reducer.js
Labels: Effort: Low, Platform: Web, Priority: Medium, Status: Completed, Type: Enhancement

#193 Update profile alert bug fixed
  frontend/src/assets/img/faces/default_image.png
  frontend/src/components/Modal/AddProjectModal.jsx
  frontend/src/views/UserProfile/UserProfile.jsx
Labels: Effort: Low, Platform: Web, Status: Completed, Type: Bug

#195 added image upload and download
  .gitignore
  backend/api/settings.py
  backend/api/urls.py
  backend/project/views.py
  backend/user/urls.py
  backend/user/views.py
Labels: Effort: Medium, Platform: API, Priority: High, Status: Review Needed, Type: Enhancement

#194 Logged in user project page
  frontend/src/components/Bids/Bids.jsx
  frontend/src/components/Card/MessageCard.jsx
  frontend/src/components/CreateBid/CreateBid.jsx
  frontend/src/layouts/Home/Home.jsx
  frontend/src/views/BaseProjectPage/BaseProjectPage.jsx
  frontend/src/views/ProjectPage/ProjectPage.jsx
Labels: Effort: Low, Platform: Web, Priority: Medium
