Repository bounswe/bounswe2018group5, pull requests merged in 2018-05, with the labels that each got.

#126 Move controls from handler to logic function.
  KarpuzTwitterApp/handlers/locationtweets.py
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/templates/locationtweets.html
Labels: Effort: Low, Priority: Medium, Status: In Progress, Type: Enhancement

#129 Add pytest for location function.
  .gitignore
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/requirements.txt
  KarpuzTwitterApp/tests/test_logic.py
Labels: Effort: Medium, Priority: Medium, Status: In Progress, Type: Maintenance

#131 Add common followers unit tests
  .gitignore
  KarpuzTwitterApp/logic.py
  KarpuzTwitterApp/tests/test_logic.py
Labels: Effort: Low, Platform: Web, Priority: Medium, Status: Available, Type: Bug, Type: Enhancement
